version: "3.8"

services:
  api:
    image: nleveryone/gis_api
    depends_on:
      - db
    ports:
      - "80:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/app:ro
    command: bash -c "python manage.py wait_for_db.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15-bullseye
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
